---
- name: new users are created
  hosts: all
  become: true
  vars:
    a: 200
  tasks:
    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts
  
    - name: Shut down Debian flavored systems
      command: "shutdown -h now"
      register: result
      ignore_errors: true
     

    - name: Show facts available on the system
      ansible.builtin.debug:
        var: result

    - name: Register a variable
      command: "cat /etc/motd"
      register: motd_contents

    - name: Show facts available on the system
      ansible.builtin.debug:
        var: motd_contents
      when: motd_contents is skipped



