# Running the playbook by providing playbook variables from  group vars and host vars
---
- name: new user is created
  hosts: server1
  become: true
  
  tasks:
  
    - name: User gets Created for "{{ username }}"
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        comment: "{{ testuser }}" 
        state: present

    - name: User gets deleted for "{{ username }}"
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        comment: "{{ testuser }}"
        state: present
   
