# Creating  Test user  ssh keys and sudoers file

  - name: add sudoers file to testuser "{{ username }}"  "{{ filename }}"
    file:
      dest: /etc/sudoers.d/"{{ username }}"
      state: absent

  - name: Copying SSH keys to all the hosts "{{ username }}"
    authorized_key:
       user: "{{ username }}"
       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC6eLTKhcRlLLsUs15pfBPFz1Sda0mS+VaLpRa+bHJFn Ansible key"
       state: absent

  - name: Create an Test User "{{ username }}"
    user:
      name: "{{ username }}"
      group: root
      state: absent
