    - name: Installing applicaition 

      block:
        - name: installing web server and open java  on Debian family
          apt:
            name:
              - apache2
              - openjdk-8-jdk
            state: present
          when: ansible_os_family=="Debian"
          notify: Reboot_systems
 
        - name: uninstalling  web server and open java  on Debian family
          apt:
            name:
              - apache2
              - openjdk-8-jdk
            state: absent
          when: ansible_os_family=="Debian"
          notify: Reboot_systems


      rescue:
        
        - name: reboot the system in rescue
          reboot:


